---
title: "Submitted Cohort Definitions"
author: "Gowtham A. Rao"
date: "`r Sys.Date()`"
output:
  html_document:
    number_sections: no
    toc: no  
  pdf_document: 
    toc: no     
vignette: >
  %\VignetteIndexEntry{Submitted Cohort Definitions}
  %\VignetteEncoding{UTF-8}    
  %\VignetteEngine{knitr::rmarkdown}
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(
  cache = FALSE,
  comment = "#>",
  error = FALSE,
  tidy = FALSE
)
```

[PhenotypeLibrary](https://github.com/OHDSI/PhenotypeLibrary) is part of [HADES](https://ohdsi.github.io/Hades/)

*This document is a DRAFT guidance.*


# Post submission

## Validity Checks prior to consideration
- Your submissions will be subjected to the following routine [Validity Checks For CohortDefinitions](https://ohdsi.github.io/PhenotypeLibrary/articles/ValidityChecksForCohortDefinitions.html)
- Your submission is expected to pass these tests prior to being posted into atlas-phenotype.ohdsi.org
  
## Addition to [Atlas-phenotype] (https://atlas-phenotype.ohdsi.org/)
- If your cohort definitions pass the validity checks, it will be posted to [Atlas-phenotype] (https://atlas-phenotype.ohdsi.org/)
- Cohort definitions will make it to [OHDSI Phenotype Library] (https://github.com/OHDSI/PhenotypeLibrary)
- The [Cohort Definitions in OHDSI Phenotype Library are here] (https://ohdsi.github.io/PhenotypeLibrary/articles/CohortDefinitionsInOhdsiPhenotypeLibrary.html) but will be flagged as 'Under review' with submission date. The added version field will be empty, as your cohort definition is not considered to be accepted.
- *NOTE: the cohort definitions in this state, are not guaranteed to be immutable. The definitions may change.*

## Assignment for Peer Review
- OHDSI will perform on open peer review through the OHDSI Phenotype Development and Evaluation workgroup.
- Workgroup members ill be assigned as peer reviewers. The peer review will be oral feedback followed by a recommendation.
- The peer review will be video recorded and the recordings will be available in the workgroup archives.
- It is up-to the submitter to then consider the peer review recommendations, make changes, or not.
- Based on the decision of the peer reviewer(s) the cohort definition would be considered accepted.
- Once accepted, the cohort definitions will be made immutable and a version number will be assigned to it. Key peer review notes will usually be referenced (commonly to the forum post).
