blank_issues_enabled: false
contact_links:
  - name: OHDSI Community
    url: https://www.ohdsi.org/
    about: OHDSI community website.
  - name: OHDSI Phenotype library
    url: https://data.ohdsi.org/PhenotypeLibrary
    about: OHDSI Phenotype library.